server:
  port: 8081


spring:
  application:
    name: backend API
  datasource:
    driver-class-name: org.h2.Driver
    username: leo
    password: 12345
    url: "jdbc:h2:mem:mybd"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: 'create-drop'
